ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080 # 更改端口
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:6666/postgres"
    user: "postgres"
    password: "954425866"